CREATE DATABASE AULA;

USE AULA;

CREATE TABLE CLIENTE(
	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	SEXO ENUM('M', 'F') NOT NULL,
	EMAIL VARCHAR(50) UNIQUE,
	CPF VARCHAR(15) UNIQUE
);

CREATE TABLE TELEFONE(
	IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
	TIPO ENUM ('COM','RES','CEL'),
	NUMERO VARCHAR(10) NOT NULL,
	ID_CLIENTE INT,
	FOREIGN KEY(ID_CLIENTE)
	REFERENCES CLIENTE(IDCLIENTE)
);

CREATE TABLE ENDERECO(
	IDENDERECO INT PRIMARY KEY AUTO_INCREMENT,
	RUA VARCHAR(30) NOT NULL,
	BAIRRO VARCHAR(30) NOT NULL,
	CIDADE VARCHAR(30) NOT NULL,
	ESTADO CHAR(2) NOT NULL,
	ID_CLIENTE INT UNIQUE,
	FOREIGN KEY(ID_CLIENTE)
	REFERENCES CLIENTE(IDCLIENTE)
);

/* CLIENTE */

INSERT INTO CLIENTE VALUES (NULL, 'JOÃO', 'M', 'JOAO@IG.COM', '000.111.222-00');
INSERT INTO CLIENTE VALUES (NULL,'MARIA', 'F', 'MARIA@GMAIL.COM', '111.000.222-11');
INSERT INTO CLIENTE VALUES (NULL,'PEDRO', 'M', 'PEDRO@HOTMAIL.COM', '222.111.000-22');
INSERT INTO CLIENTE VALUES (NULL,'MADALENA', 'F', 'MADA@MAIL.COM', '333.222.111-33');
INSERT INTO CLIENTE VALUES (NULL,'JONAS', 'M', NULL, '321.545.234-15');
INSERT INTO CLIENTE VALUES (NULL,'MELINA', 'F', NULL, '765.345.765-21');
INSERT INTO CLIENTE VALUES (NULL,'LAURA', 'F', NULL, '543.577.987-09');

SELECT * FROM CLIENTE;

/* ENDEREÇO*/

INSERT INTO ENDERECO VALUES (NULL, 'RUA A', 'CENTRO', 'BELO HORIZONTE', 'MG','1');
INSERT INTO ENDERECO VALUES (NULL, 'RUA B', 'CANUDOS', 'BELEM', 'PA','2');
INSERT INTO ENDERECO VALUES (NULL, 'RUA C', 'CASTANHEIRAS', 'ARAPARI', 'ES','3');
INSERT INTO ENDERECO VALUES (NULL, 'RUA A', 'CENTRO', 'SÃO PAULO', 'SP','4');
INSERT INTO ENDERECO VALUES (NULL, 'RUA A', 'ESTACIO', 'SÃO PAULO', 'SP','5');
INSERT INTO ENDERECO VALUES (NULL, 'RUA A', 'CENTRO', 'BELO HORIZONTE', 'SP','6');
INSERT INTO ENDERECO VALUES (NULL, 'RUA A', 'CENTRO', 'BELÉM', 'SP','7');

SELECT * FROM ENDERECO;

/* TELEFONE*/

INSERT INTO TELEFONE VALUES (NULL, 'CEL', '98888-0000','1');
INSERT INTO TELEFONE VALUES (NULL, 'RES', '3333-4444','1');
INSERT INTO TELEFONE VALUES (NULL, 'COM', '2222-3333', '2');
INSERT INTO TELEFONE VALUES (NULL, 'RES', '2121-4343','2');
INSERT INTO TELEFONE VALUES (NULL, 'RES', '3232-4545','3');
INSERT INTO TELEFONE VALUES (NULL, 'COM', '9090-8787','3');
INSERT INTO TELEFONE VALUES (NULL, 'CEL', '98989-2111','1');
INSERT INTO TELEFONE VALUES (NULL, 'CEL', '98080-1010','4');
INSERT INTO TELEFONE VALUES (NULL, 'COM', '97878-3131','4');
INSERT INTO TELEFONE VALUES (NULL, 'RES', '3333-1010','5');
INSERT INTO TELEFONE VALUES (NULL, 'CEL', '98766-5352','7');
INSERT INTO TELEFONE VALUES (NULL, 'CEL', '99193-8796','6');


SELECT * FROM TELEFONE;


/* QUERIES - SELEÇÃO - PROJEÇÃO - JUNÇÃO */

/* IFNULL */

SELECT C.NOME, IFNULL(C.EMAIL, 'SEM EMAIL') AS "EMAIL",
T.NUMERO  
FROM CLIENTE C
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE
WHERE SEXO='F' AND ESTADO='SP';


/* SEÇÃO 08 AULA 29 - TRABALHANDO COM VIEWS */


SELECT  C.NOME, C.SEXO,
		IFNULL(C.EMAIL, 'SEM EMAIL') AS "EMAIL",
		T.TIPO,
		T.NUMERO,
		E.BAIRRO,
		E.CIDADE,
		E.ESTADO  
FROM CLIENTE C
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE;



/* CRIANDO A VIEW */

CREATE VIEW V_RELATORIO AS
SELECT  C.NOME, C.SEXO,
		IFNULL(C.EMAIL, 'SEM EMAIL') AS "EMAIL",
		T.TIPO,
		T.NUMERO,
		E.BAIRRO,
		E.CIDADE,
		E.ESTADO  
FROM CLIENTE C
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE;


SELECT NOME, SEXO, EMAILFROM V_RELATORIO;

/* APAGANDO A VIEW */

DROP VIEW RELATORIO;