/* SEÇÃO 12 AULA 38 - MODIFICANDO UMA TABELA - ALTER TABLE */


CREATE TABLE TABELA(
	COLUNA1 VARCHAR(10),
	COLUNA2 VARCHAR(10),
	COLUNA3 VARCHAR(10)
);


/* ADICIONANDO UMA PRIMARY KEY */

ALTER TABLE TABELA 
ADD PRIMARY KEY (COLUNA1); 

/* ADICIONANDO UMA COLUNA SEM POSIÇÃO, ULTIMA POSIÇÃO */

ALTER TABLE TABELA 
ADD COLUNA VARCHAR(10); 

ALTER TABLE TABELA 
ADD COLUNA100 INT; 


/* ADICIONANDO UMA COLUNA COM POSIÇÃO */

ALTER TABLE TABELA
ADD COLUMN COLUNA4 VARCHAR(10) NOT NULL UNIQUE
AFTER COLUNA3;


/* MODIFICANDO O NOME DE UM CAMPO */

ALTER TABLE TABELA MODIFY COLUNA2 DATE NOT NULL;

/* RENOMEANDO O NOME DE UMA TABELA */

ALTER TABLE TABELA 
RENAME PESSOA;


CREATE TABLE TIME(
	IDTIME INT PRIMARY KEY AUTO_INCREMENT,
	TIME VARCHAR(30),
	ID_PESSOA VARCHAR(30)
);

ALTER TABLE TIME
ADD FOREIGN KEY(ID_PESSOA)
REFERENCES PESSOA(COLUNA1);

/* VERIFICANDO AS CHAVES */

SHOW CREATE TABLE TIME; 




/* SEÇÃO 12 AULA 40 - CONSTRAINTS NOMEADAS X DICIONARIO DE DADOS */


SHOW TABLES;

DROP TABLE ENDEREÇO;

DROP TABLE TELEFONE;

DROP TABLE CLIENTE;

CREATE TABLE CLIENTE(
	IDCLIENTE INT,
	NOME VARCHAR(30)
);

CREATE TABLE TELEFONE(
	IDTELEFONE INT,
	TIPO CHAR(3) NOT NULL,
	NUMERO VARCHAR(10) NOT NULL,
	ID_CLIENTE INT
);

ALTER TABLE CLIENTE ADD CONSTRAINT PK_CLIENTE
PRIMARY KEY (IDCLIENTE);

ALTER TABLE TELEFONE ADD CONSTRAINT FK_CLIENTE_TELEFONE
FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(IDCLIENTE);

SHOW CREATE TABLE TELEFONE;



/* DICIONARIO DE DADOS */

SHOW DATABASES;

USE INFORMATION_SCHEMA;

DESC TABLE_CONSTRAINTS;