/* MODELAGEM DE CLIENTE*/

CREATE DATABASE COMERCIO;

USE COMERCIO;

CREATE TABLE CLIENTE(
	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	SEXO ENUM('M', 'F') NOT NULL,
	EMAIL VARCHAR(50) UNIQUE,
	CPF VARCHAR(15) UNIQUE
);

CREATE TABLE TELEFONE(
	IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
	TIPO ENUM ('COM','RES','CEL'),
	NUMERO VARCHAR(10) NOT NULL,
	ID_CLIENTE INT,
	FOREIGN KEY(ID_CLIENTE)
	REFERENCES CLIENTE(IDCLIENTE)
);

CREATE TABLE ENDERECO(
	IDENDERECO INT PRIMARY KEY AUTO_INCREMENT,
	RUA VARCHAR(30) NOT NULL,
	BAIRRO VARCHAR(30) NOT NULL,
	CIDADE VARCHAR(30) NOT NULL,
	ESTADO CHAR(2) NOT NULL,
	ID_CLIENTE INT UNIQUE,
	FOREIGN KEY(ID_CLIENTE)
	REFERENCES CLIENTE(IDCLIENTE)
);



/* FOREING KEY - CHAVE ESTRANGEIRA - FK */


/* É A CHAVE PRIMÁRIA DE UMA TABELA, QUE VAI ATÉ OUTRA TABELA FAZER REFERÊNCIA  */


/* EM RELACIONAMENTO 1X1 A CHAVE ESTRANGEIRA FICA NA TABELA MAIS FRACA */

/* EM RELACIONAMENTO 1XN A CHAVE ESTRANGEIRA FICA NA TABELA N */


/* CLIENTE */

INSERT INTO CLIENTE (NOME, SEXO, EMAIL, CPF) VALUES ('JOÃO', 'M', 'JOAO@IG.COM', '000.111.222-00');
INSERT INTO CLIENTE (NOME, SEXO, EMAIL, CPF) VALUES ('MARIA', 'F', 'MARIA@GMAIL.COM', '111.000.222-11');
INSERT INTO CLIENTE (NOME, SEXO, EMAIL, CPF) VALUES ('PEDRO', 'M', 'PEDRO@HOTMAIL.COM', '222.111.000-22');
INSERT INTO CLIENTE (NOME, SEXO, EMAIL, CPF) VALUES ('MADALENA', 'F', 'MADA@MAIL.COM', '333.222.111-33');

SELECT * FROM CLIENTE;

/* ENDEREÇO*/

INSERT INTO ENDERECO VALUES (NULL, 'RUA A', 'CENTRO', 'BELO HORIZONTE', 'MG','2');
INSERT INTO ENDERECO VALUES (NULL, 'RUA B', 'CANUDOS', 'BELEM', 'PA','3');
INSERT INTO ENDERECO VALUES (NULL, 'RUA C', 'CASTANHEIRAS', 'ARAPARI', 'ES','1');
INSERT INTO ENDERECO VALUES (NULL, 'RUA A', 'CENTRO', 'SÃO PAULO', 'SP','4');

SELECT * FROM ENDERECO;

/* TELEFONE*/

INSERT INTO TELEFONE VALUES (NULL, 'CEL', '98888-0000','1');
INSERT INTO TELEFONE VALUES (NULL, 'RES', '3333-4444','1');
INSERT INTO TELEFONE VALUES (NULL, 'COM', '2222-3333', '2');
INSERT INTO TELEFONE VALUES (NULL, 'RES', '2121-4343','2');
INSERT INTO TELEFONE VALUES (NULL, 'RES', '3232-4545','3');
INSERT INTO TELEFONE VALUES (NULL, 'COM', '9090-8787','3');
INSERT INTO TELEFONE VALUES (NULL, 'CEL', '98989-2111','1');


SELECT * FROM TELEFONE;