/* SEÇÃO 15 AULA 45 - TRIGGERS */

/* ESTRUTURA DE UMA TRIGGER - GATILHO */


DELIMIT $

CREATE TRIGGER NOME
BEFORE/AFTER INSERT/DELETE/UPDATE ON TABELA
FOR EACH ROW (PARA CADA LINHA)
BEGIN -> INICIO

	QUALQUER COMANDO SQL

END -> FIM

CREATE DATABASE AULA_46;

USE AULA_46;

CREATE TABLE USUARIO(
	IDUSUARIO INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30),
	LOGIN VARCHAR(30),
	SENHA VARCHAR(30)
);

CREATE TABLE BKP_USUARIO(
	IDBACKUP INT PRIMARY KEY AUTO_INCREMENT,
	IDUSUARIO INT,
	NOME VARCHAR(30),
	LOGIN VARCHAR(30)
);


/* TRIGGER */


DELIMITER $

CREATE TRIGGER BACKUP_USER
BEFORE DELETE ON USUARIO
FOR EACH ROW 
BEGIN 

	INSERT INTO BKP_USUARIO VALUES 
	(NULL, OLD.IDUSUARIO, OLD.NOME, OLD.LOGIN);

END 
$

DELIMITER ;

INSERT INTO USUARIO VALUES (NULL, 'JUAN', 'JUAN2017', 'JUANBARATA');

DELETE FROM USUARIO WHERE IDUSUARIO='1';

SELECT * FROM BKP_USUARIO; 