/* EXERCÍCIO DE FIXAÇÃO */

/* 1 - CRIE UM BANCO DE DADOS CHAMADO PROJETO E CONECTE-SE AO BANCO */
/* 2 - FAÇA A SEGUINTE MODELAGEM */

/* SR JOSÉ QUER MODERNIAR A SUA OFICINA, E POR ENQUANTO, CADASTRAR OS CARROS QUE ENTRAM PARA
REALIZAR OS SERVIÇOS E OS SEUS RESPECTIVOS DONOS. 
SR JOSÉ MENCIONOU QUE:
- CADA CLIENTE POSSUI APENAS UM CARRO. 
- UM CARRO POSSUI UMA MARCA. 
- SR JOSÉ TAMBÉM QUER SABER AS CORES DOS CARROS PARA TE IDÉIA DE QUAL TINTA COMPRAR, E INFORMA QUE UM CARRO PODE TER MAIS DE UMA COR.
- SR JOSÉ NECESSITA ARMAZENAR OS TELEFONES DOS CLIENTES, MAS NÃO QUER QUE ELES SEJAM OBRIGATÓRIOS. */

CREATE DATABASE PROJETO_JOSE;

USE PROJETO_JOSE;

SELECT NOW() AS "DATA";


CREATE TABLE CLIENTE(
	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL
);

CREATE TABLE CARRO(
	IDCARRO INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	ID_CLIENTE INT UNIQUE,
	FOREIGN KEY (ID_CLIENTE)
	REFERENCES CLIENTE (IDCLIENTE)
);

CREATE TABLE TELEFONE(
	IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
	NUMERO VARCHAR(10),
	ID_CLIENTE INT,
	FOREIGN KEY (ID_CLIENTE)
	REFERENCES CLIENTE (IDCLIENTE)
);

CREATE TABLE MARCA(
	IDMARCA INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	ID_CARRO INT UNIQUE,
	FOREIGN KEY (ID_CARRO)
	REFERENCES CARRO (IDCARRO)
);

CREATE TABLE COR(
	IDCOR INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(10) NOT NULL,
	ID_CARRO INT,
	FOREIGN KEY (ID_CARRO)
	REFERENCES CARRO (IDCARRO)
);

INSERT INTO CLIENTE (NOME) VALUES ('JUAN BARATA');
INSERT INTO CLIENTE (NOME) VALUES ('JEAN BARATA FILHO');
INSERT INTO CLIENTE (NOME) VALUES ('ADRIA BARATA');

SELECT * FROM CLIENTE;

INSERT INTO TELEFONE (NUMERO, ID_CLIENTE) VALUES ('984431181', '1');
INSERT INTO TELEFONE (NUMERO, ID_CLIENTE) VALUES ('327415554', '1');
INSERT INTO TELEFONE (NUMERO, ID_CLIENTE) VALUES ('988887777', '2');
INSERT INTO TELEFONE (NUMERO, ID_CLIENTE) VALUES ('985553333', '3');
INSERT INTO TELEFONE (NUMERO, ID_CLIENTE) VALUES ('986871212', '3');
INSERT INTO TELEFONE (NUMERO, ID_CLIENTE) VALUES ('373443434', '3');

SELECT * FROM TELEFONE;

INSERT INTO CARRO (NOME, ID_CLIENTE) VALUES ('PALIO ELX 1.0 10/10', '1');
INSERT INTO CARRO (NOME, ID_CLIENTE) VALUES ('CIVIC LXS 1.8 18/18', '2');
INSERT INTO CARRO (NOME, ID_CLIENTE) VALUES ('CITY 19/18', '3');

SELECT * FROM CARRO;

INSERT INTO MARCA (NOME, ID_CARRO) VALUES ('FIAT', '1');
INSERT INTO MARCA (NOME, ID_CARRO) VALUES ('HONDA', '2');
INSERT INTO MARCA (NOME, ID_CARRO) VALUES ('HONDA', '3');
INSERT INTO MARCA (NOME, ID_CARRO) VALUES ('HONDA', '3');

SELECT * FROM MARCA;

INSERT INTO COR (NOME, ID_CARRO) VALUES ('CINZA', '1');
INSERT INTO COR (NOME, ID_CARRO) VALUES ('CHUMBO', '2');
INSERT INTO COR (NOME, ID_CARRO) VALUES ('PEROLADO', '2');
INSERT INTO COR (NOME, ID_CARRO) VALUES ('PRETO', '3');

SELECT * FROM COR;

SELECT C.NOME AS NOME_CLIENTE,
T.NUMERO AS NUMERO_TELEFONE,
CAR.NOME AS NOME_CARRO,
M.NOME AS MARCA_CARRO,
CO.NOME AS COR_CARRO
FROM CLIENTE C
INNER JOIN TELEFONE T
ON T.ID_CLIENTE = C.IDCLIENTE
INNER JOIN CARRO CAR
ON CAR.ID_CLIENTE = C.IDCLIENTE
INNER JOIN MARCA M
ON M.ID_CARRO = CAR.IDCARRO 
INNER JOIN COR CO
ON CO.ID_CARRO = CAR.IDCARRO;