/* Modelagem básica */

CLIENTE

NOME CARACTER (30)
CPF NUMERICO (11)
EMAIL CARACTER (30)
TELEFONE CARACTER (30)
SEXO CARACTER (1)
ENDERECO CARACTER (100)

/*Processos de modelagem*/

/* ADM DE DADOS */
MODELAGEM CONCEITUAL - RASCUNHOS
MODELAGEM LÓGICA - PROGRAMAS COM BRMODELO

/* AD - DBA */
MODELAGEM FÍSICA - SCRIPT DO BANCO

/* MODELO FÍSICO */

/* CRIANDO UM BANCO DE DADOS */

CREATE DATABASE PROJETO;

/* CONECTANDO */

USE PROJETO;

/* CRIANDO TABELA */

CREATE TABLE CLIENTE(
	NOME VARCHAR(30),
	SEXO CHAR(1),
	EMAIL VARCHAR(30),
	CPF INT(11),
	TELEFONE VARCHAR(30),
	ENDERECO VARCHAR(100)
);

/*VERIFICANDO AS TABELAS*/

SHOW TABLES;

/*DESCREVENDO AS TABELAS*/

DESC CLIENTE;



/* SEÇÃO 03 AULA 10 - COMANDO INSERT */

/*INSERT FORMA 01 - EXCLUINDO AS COLUNAS*/

INSERT INTO CLIENTE VALUES ('JUAN BARATA', 'M', 'JUAN.BARATA.SI@GMAIL.COM', 02055178202, '984431181', 'CONJ XINGU, QD 22, N 135');

INSERT INTO CLIENTE VALUES ('JEAN BARATA FILHO', 'M', 'JEAN.BARATA.FILHO@HOTMAIL.COM', 11133312390, '989664534', 'DR. SILVA ROSADO, N 360');

/*INSERT FORMA 02 - COLOCANDO AS COLUNAS*/

INSERT INTO CLIENTE (NOME, SEXO, TELEFONE) VALUES ('LEONARDO WALLACE', 'M', '988445512');

INSERT INTO CLIENTE (NOME, SEXO, EMAIL, CPF, TELEFONE, ENDERECO) VALUES ('ADRIA JUANA', 'F', 'DRIH_NASCIMENTO@HOTMAIL.COM', 0123456789, '985517788', 'DR. SILVA ROSADO, N 360');





/* SEÇÃO 03 AULA 11 - COMANDO SELECT */

SELECT NOW();

SELECT 'JUAN BARATA';

SELECT 'BANCO DE DADOS';

/* ALIAS DE COLUNAS */

SELECT 'JUAN BARATA' AS 'PROFESSOR';

SELECT NOME, SEXO, EMAIL, CPF, TELEFONE, ENDERECO FROM CLIENTE;

/* APENAS PARA FINS ACADÊMICOS */

SELECT * FROM CLIENTE;




/* SEÇÃO 03 AULA 12 - FILTRANDO DADOS COM O COMANDO WHERE */

SELECT NOME, EMAIL, CPF FROM CLIENTE WHERE SEXO='M';

 SELECT NOME, EMAIL, CPF FROM CLIENTE WHERE SEXO='F';

 /* UTILIZANDO LIKE % */

 SELECT NOME, ENDERECO FROM CLIENTE WHERE ENDERECO LIKE '%DR%'; 




 /* SEÇÃO 03 AULA 13 - FILTRANDO DADOS COM O COMANDO WHERE USANDO OPERADORES LÓGICOS */

 /* OR -> OU */

 SELECT NOME, EMAIL, ENDERECO FROM CLIENTE WHERE SEXO='M' OR ENDERECO LIKE '%DR%';

 /* AND -> E */

 SELECT NOME, EMAIL, ENDERECO FROM CLIENTE WHERE SEXO='M' AND ENDERECO LIKE '%DR%';




/* SEÇÃO 03 AULA 14 - CONTANDO E AGRUPANDO UTILIZANDO COUNT E GROUP BY */

/* CONTANDO OS REGISTROS DE UMA TABELA */

SELECT COUNT(*) FROM CLIENTE;

SELECT COUNT(*) AS "QUANTIDADE DE REGISTROS DA TABELA CLIENTE" FROM CLIENTE;

/* OPERADOR GROUP BY */

SELECT SEXO, COUNT(*) AS "QUANTIDADE" FROM CLIENTE GROUP BY SEXO;



/* SEÇÃO 03 AULA 15 - FILTRANDO VALORES NULOS */

SELECT NOME, SEXO, ENDERECO FROM CLIENTE WHERE EMAIL IS NULL;

SELECT NOME, SEXO, ENDERECO FROM CLIENTE WHERE EMAIL IS NOT NULL;



/* SEÇÃO 04 AULA 16 - ATUALIZANDO OS CAMPOS COM UPDATE */

UPDATE CLIENTE SET EMAIL = 'JUAN.BARATA@HOTMAIL.COM' WHERE NOME='JUAN BARATA';



/* SEÇÃO 04 AULA 17 - EXCLUINDO OS CAMPOS COM DELETE */

DELETE FROM CLIENTE WHERE NOME='JUAN BARATA'; 



/* SEÇÃO 05 AULA 20 - MODELAGEM - PRIMEIRA FORMA NORMAL*/


/* 1 - TODO CAMPO VETORIZADO SE TORNARÁ UMA TABELA */

/* 2 - TODO CAMPO MULTIVALORADO SE TORNARÁ UMA TABELA */

/* 3 - TODO TABELA NECSSITA DE PELO MENOS UM CAMPO QUE IDENTIFIQUE TODO O REGISTRO COMO SENDO ÚNICO - CHAVE PRIMÁRIA OU PRIMARI KEY  */




/* CARDINALIDADE */

/* QUEM DEFINE A CARDINALIDADE É A REGRA DE NEGÓCIO */


/* PRIMEIRO ALGARISMO - OBRIGATORIEDADE */
0 - NÃO OBRIGATÓRIO
1 - OBRIGATÓRIO


/* SEGUNDO ALGORISMO - CARDINALIDADE */
1 - MÁXIMO
N - MAIS DE UM
