/* CRIANDO PROCEDURES COM PARÂMETROS */

DELIMITER $

CREATE PROCEDURE CONTA(N1 INT, N2 INT)
BEGIN
		SELECT N1 + N2 AS 'CONTA';
END
$

DELIMITER ;

CALL CONTA (100, 78);

/* AULA 28 - PROCEDURES COM TABELAS */

CREATE TABLE CURSOS(
	IDCURSO INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	HORAS INT(3) NOT NULL,
	VALOR FLOAT(10,2) NOT NULL
);


INSERT INTO CURSOS VALUES (NULL, 'BANCO DE DADOS FUNDAMENTAL', 25, 200.00);

SELECT * FROM CURSOS;





DELIMITER $

CREATE PROCEDURE CAD_CURSOS (P_NOME VARCHAR(30), P_HORAS INT(3), P_VALOR FLOAT(10,2))
BEGIN
		INSERT INTO CURSOS VALUES (NULL, P_NOME, P_HORAS, P_VALOR);
END
$

DELIMITER ;

CALL CAD_CURSOS ('BI SQL SERVER', 35, 200.00);

SELECT * FROM CURSOS;


DELIMITER $

CREATE PROCEDURE SEL_CURSOS ()
BEGIN
		SELECT IDCURSO, NOME, HORAS, VALOR
		FROM CURSOS; 
END
$

DELIMITER ;

CALL SEL_CURSOS();



/*  SEÇÃO 10 - AULA 34  */

CREATE TABLE VENDEDORES (
	IDVENDEDOR INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30),
	SEXO CHAR(1),
	JANEIRO FLOAT(10,2),
	FEVEREIRO FLOAT(10,2),
	MARCO FLOAT(10,2)
);

INSERT INTO VENDEDORES VALUES (NULL, 'CARLOS', 'M', 10432.45, 43242.90, 2441.50);
INSERT INTO VENDEDORES VALUES (NULL, 'MARIA', 'F', 524524.45, 1345346.90, 1656.50);
INSERT INTO VENDEDORES VALUES (NULL, 'ANTONIO', 'M', 45345.45, 4541351.90, 56522.50);
INSERT INTO VENDEDORES VALUES (NULL, 'CLARA', 'F', 5514354.45, 432413152.90, 1153462.50);
INSERT INTO VENDEDORES VALUES (NULL, 'ANDERSON', 'M', 63465426.45, 2656526.90, 624542.50);
INSERT INTO VENDEDORES VALUES (NULL, 'IVONE', 'F', 54532525.45, 43242.90, 2441.50);
INSERT INTO VENDEDORES VALUES (NULL, 'JOAO', 'M', 3423515.45, 134341.90, 13414.50);
INSERT INTO VENDEDORES VALUES (NULL, 'CELIA', 'F', 45314.45, 34134.90, 34531.50);

/* MAX - TRAZ O VALOR MÁXIMO DE UMA COLUNA */

SELECT  MAX(FEVEREIRO) AS MAIOR_FEV
		FROM VENDEDORES;

/* MIN - TRAZ O VALOR MÍNIMO DE UMA COLUNA */

SELECT  MIN(FEVEREIRO) AS MENOR_FEV
		FROM VENDEDORES;

/* AVG - TRAZ O VALOR MÉDIO DE UMA COLUNA */

SELECT  AVG(FEVEREIRO) AS MEDIA_FEV
		FROM VENDEDORES;

/* VÁRIAS FUNÇÕES */

SELECT  MAX(JANEIRO) AS MAX_JAN,
		MIN(JANEIRO) AS MENOR_JAN,
		AVG(JANEIRO) AS MEDIA_JAN
		FROM VENDEDORES;

/* TRUNCATE */

SELECT  MAX(JANEIRO) AS MAX_JAN,
		MIN(JANEIRO) AS MENOR_JAN,
		TRUNCATE (AVG(JANEIRO),2) AS MEDIA_JAN
		FROM VENDEDORES;


/* AULA 35 - UTILIZANDO SUM */

SELECT  SEXO, SUM(JANEIRO) AS SOMA_JAN,
		SUM(FEVEREIRO) AS SOMA_FEV,
		SUM(MARCO) AS SOMA_MAR 
		FROM VENDEDORES
		GROUP BY SEXO;



/* AULA 36 - SUBQUERY */

/* VENDEDOR QUE VENDEU MENOS EM MARÇO E O SEU NOME */

SELECT NOME, MARCO FROM VENDEDORES
WHERE MARCO = (SELECT MIN(MARCO) FROM VENDEDORES);

/* VENDEDOR QUE VENDEU MAIS EM MARÇO E O SEU NOME */

SELECT NOME, MARCO FROM VENDEDORES
WHERE MARCO = (SELECT MAX(MARCO) FROM VENDEDORES);

/* VENDEDOR QUE VENDEU MAIS QUE A MÉDIA DE FEVEREIRO E O SEU NOME */

SELECT NOME, FEVEREIRO FROM VENDEDORES
WHERE FEVEREIRO > (SELECT AVG(FEVEREIRO) FROM VENDEDORES);

SELECT NOME, FEVEREIRO FROM VENDEDORES
WHERE FEVEREIRO < (SELECT AVG(FEVEREIRO) FROM VENDEDORES);


/* AULA 37 - OPERAÇÕES EM LINHA */

SELECT  NOME,
		JANEIRO,
		FEVEREIRO,
		MARCO,
		(JANEIRO+FEVEREIRO+MARCO) AS "TOTAL",
		TRUNCATE(((JANEIRO+FEVEREIRO+MARCO)/3), 2) AS "MEDIA"
		FROM VENDEDORES;


SELECT  NOME,
		JANEIRO,
		FEVEREIRO,
		MARCO,
		(JANEIRO+FEVEREIRO+MARCO) AS "TOTAL",
		(JANEIRO+FEVEREIRO+MARCO) * .25 AS "DESCONTO",
		TRUNCATE(((JANEIRO+FEVEREIRO+MARCO)/3), 2) AS "MEDIA"
		FROM VENDEDORES;


		