/* Seção 06 Aula 25 */

/* SELEÇÃO, PROJEÇÃO E JUNÇÃO */



/* PROJEÇÃO - TUDO QUE QUEREMOS PROJETAR NA TELA */

USE COMERCIO;

SELECT NOW() AS "DATA";

SELECT NOME, NOW() AS "DATA" FROM CLIENTE;



/* SELEÇÃO - TEORIA DOS CONJUNTOS - WHERE É A CLAUSULA DA SELEÇÃO */

SELECT NOME, SEXO FROM CLIENTE WHERE SEXO='F';


/* JUNÇÃO - JOIN */

/* NOME, SEXO, BAIRRO, CIDADE, DATA */

SELECT NOME, SEXO, BAIRRO, CIDADE /* PROJEÇÃO */
FROM CLIENTE 
INNER JOIN ENDERECO  /* JUNÇÃO */
ON IDCLIENTE = ID_CLIENTE; /* SELEÇÃO */


/* CLAUSULA AMBIGUA */

SELECT CLIENTE.IDCLIENTE, CLIENTE.NOME, CLIENTE.SEXO, 
ENDERECO.BAIRRO, ENDERECO.CIDADE, 
TELEFONE.TIPO, TELEFONE.NUMERO
FROM CLIENTE
INNER JOIN ENDERECO
ON CLIENTE.IDCLIENTE = ENDERECO.ID_CLIENTE 
INNER JOIN TELEFONE
ON CLIENTE.IDCLIENTE = TELEFONE.ID_CLIENTE;

SELECT C.IDCLIENTE, C.NOME, C.SEXO, 
E.BAIRRO, E.CIDADE, 
T.TIPO, T.NUMERO
FROM CLIENTE C
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE 
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE
WHERE SEXO='F';